version: "3.8"
services:
  database:
    image: postgres:16
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - gogame-data:/var/lib/postgres/data
      - gogame-database.conf:/var/lib/postgres/data/postgresql.conf
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - PGUSER=$DB_USER
      - PGPORT=$DB_PORT
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
        interval: 3s
        timeout: 5s
        retries: 5

  cache:
    depends_on:
      - database
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - gogame-cache:/var/lib/redis
      - gogame-cache.conf:/etc/redis/redis.conf

  backend:
    depends_on:
      - database
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000


volumes:
  gogame-data:
  gogame-database.conf:
  gogame-cache:
  gogame-cache.conf: