version: "3.8"
services:
  database:
    image: postgres:16
    volumes:
      - gogame-data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - PGUSER=$DB_USER
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
        interval: 3s
        timeout: 5s
        retries: 5
    expose:
      - 5432
    ports:
      - 5433:5432

  backend:
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000


volumes:
  gogame-data: